version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - /home/vagrant/data/mysqldb:/var/lib/mysql

  spring_app:
    image: achatproject
    container_name: achatproject
    restart: on-failure
    ports:
      - 9091:9091
    depends_on:
      - mysqldb
    
  jenkins:
   container_name: jenkins
   image: jenkins/jenkins:lts
   restart: on-failure
   ports:
      - 8080:8080
   volumes:
      - /home/vagrant/data/jenkins:/var/jenkins_home

   nexus:
   container_name:nexus
   image:sonatype/nexus3
   restart: on-failure
   ports:
      - 8081:8081
   volumes:
      - /home/vagrant/data/nexus:/nexus-data
      depends_on:
      - jenkins