version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - /home/data/mysqldb:/var/lib/mysql

  spring_app:
    image: wajihrjb/springproject:1.1
    container_name: spring
    restart: on-failure
    ports:
      - 9091:9091
    depends_on:
      - mysqldb