version: "3"

services:
  mysqldb:
    container_name: mysqldba
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    
    volumes:
      - /home/data/mysqldb:/var/lib/mysql

  spring_app:
    image: spring-image
    container_name: spring
    restart: on-failure
    ports:
      - 9091:9091
    depends_on:
      - mysqldb
